/**
 * Minimal Axosoft REST client — only what defect filing needs.
 *
 * ---------------------------------------------------------------------------
 * VERIFY THIS AGAINST YOUR INSTANCE BEFORE TRUSTING IT.
 *
 * Axosoft's API shape varies between v5/v6 and between hosted and on-premise
 * installs, and field ids (priority, workflow step, item type) are per-account.
 * Everything version-specific is deliberately confined to this file, and marked
 * with VERIFY comments.
 *
 * Run `npm run axosoft:verify` first. It is read-only: it authenticates, lists
 * your projects and priorities, and prints the ids to put in .env. If the
 * payload shape below is wrong for your instance, that script tells you before
 * anything gets written.
 * ---------------------------------------------------------------------------
 */

export interface AxosoftConfig {
  /** e.g. https://acme.axosoft.com (hosted) or http://server/axosoft (on-prem) */
  baseUrl: string;
  apiVersion: string;
  /**
   * An access token obtained earlier, if you have one. Optional.
   *
   * Note: Axosoft has NO "personal access token" feature. The normal path is
   * the client id/secret + username/password below, which this client exchanges
   * for a token on each run. This field only exists so a token acquired some
   * other way can be reused.
   */
  token?: string;
  /**
   * OAuth2 credentials. An Axosoft ADMIN generates these under
   * Tools → System Options → Axosoft API Settings → Manage API Keys.
   * The username/password grant is only permitted for *private* client apps.
   */
  clientId?: string;
  clientSecret?: string;
  username?: string;
  password?: string;
  projectId: number;
  /** Optional defaults applied to every created defect. */
  priorityId?: number;
  assignedToId?: number;
  releaseId?: number;
}

export interface AxosoftItem {
  id: number;
  name?: string;
  workflow_step?: { id: number; name: string };
}

export class AxosoftError extends Error {
  constructor(message: string, readonly status?: number, readonly body?: string) {
    super(message);
    this.name = 'AxosoftError';
  }
}

export class AxosoftClient {
  private accessToken?: string;

  constructor(private readonly config: AxosoftConfig) {}

  private get apiRoot(): string {
    return `${this.config.baseUrl.replace(/\/+$/, '')}/api/${this.config.apiVersion}`;
  }

  /**
   * Exchanges the configured credentials for a bearer token, via the OAuth2
   * username/password grant.
   *
   * Note `scope: 'read write'` — Axosoft defaults to read-only, and a token
   * without write scope fails at defect creation rather than here, which is a
   * confusing place to discover it.
   */
  async authenticate(): Promise<void> {
    if (this.config.token) {
      this.accessToken = this.config.token;
      return;
    }

    const { clientId, clientSecret, username, password } = this.config;
    if (!clientId || !clientSecret || !username || !password) {
      throw new AxosoftError(
        'Axosoft credentials are incomplete. Set AXOSOFT_CLIENT_ID, AXOSOFT_CLIENT_SECRET, ' +
          'AXOSOFT_USERNAME and AXOSOFT_PASSWORD. The client id/secret are generated by an ' +
          'Axosoft admin under Tools → System Options → Axosoft API Settings → Manage API Keys.',
      );
    }

    const params = {
      grant_type: 'password',
      client_id: clientId,
      client_secret: clientSecret,
      username,
      password,
      scope: 'read write',
    };

    const res = await this.requestToken(params);

    if (!res.ok) {
      const body = await safeText(res);
      throw new AxosoftError(
        `Axosoft authentication failed (${res.status}). Common causes: the API is not ` +
          'enabled in System Options; the API key is registered as a "public" application ' +
          '(the password grant is only allowed for private ones); or the credentials are wrong.',
        res.status,
        body,
      );
    }

    const body = (await res.json()) as { access_token?: string };
    if (!body.access_token) {
      throw new AxosoftError('Axosoft returned no access_token', res.status, JSON.stringify(body));
    }
    this.accessToken = body.access_token;
  }

  /**
   * Axosoft documents the token endpoint as a GET with query parameters, which
   * would put the password in the URL — and therefore in server and proxy logs.
   *
   * So we try POST with a form body first, which most OAuth2 implementations
   * accept, and fall back to the documented GET only if the server rejects it.
   * That keeps credentials out of logs wherever the server allows it.
   */
  private async requestToken(params: Record<string, string>): Promise<Response> {
    const url = `${this.config.baseUrl.replace(/\/+$/, '')}/api/oauth2/token`;

    const posted = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams(params),
    }).catch(() => null);

    if (posted?.ok) return posted;

    // 404/405/400 here means this instance wants the documented GET form.
    return fetch(`${url}?${new URLSearchParams(params)}`, { method: 'GET' });
  }

  private async request<T>(path: string, init: RequestInit = {}): Promise<T> {
    if (!this.accessToken) await this.authenticate();

    const res = await fetch(`${this.apiRoot}${path}`, {
      ...init,
      headers: {
        Authorization: `Bearer ${this.accessToken}`,
        'Content-Type': 'application/json',
        Accept: 'application/json',
        ...(init.headers ?? {}),
      },
    });

    if (!res.ok) {
      throw new AxosoftError(
        `Axosoft ${init.method ?? 'GET'} ${path} failed with ${res.status}`,
        res.status,
        await safeText(res),
      );
    }
    return (await res.json()) as T;
  }

  /* -- read-only, used by the verify script -------------------------- */

  async listProjects(): Promise<AxosoftItem[]> {
    const body = await this.request<{ data?: AxosoftItem[] }>('/projects');
    return body.data ?? [];
  }

  async listPriorities(): Promise<AxosoftItem[]> {
    const body = await this.request<{ data?: AxosoftItem[] }>('/picklists/priorities');
    return body.data ?? [];
  }

  /* -- deduplication -------------------------------------------------- */

  /**
   * Finds defects already carrying a fingerprint marker.
   *
   * The marker is embedded in the description by defect-content.ts, so this is
   * a plain full-text search rather than a custom-field lookup — which keeps it
   * working on accounts that have no spare custom field.
   *
   * VERIFY: `search_string` is the documented free-text filter on v5/v6. If your
   * instance ignores it, this returns everything and dedup silently over-matches
   * — which is why the verify script checks it explicitly.
   */
  async findDefectsByFingerprint(fingerprint: string): Promise<AxosoftItem[]> {
    const params = new URLSearchParams({
      search_string: fingerprint,
      columns: 'id,name,workflow_step',
      page_size: '25',
    });
    const body = await this.request<{ data?: AxosoftItem[] }>(`/defects?${params}`);
    const matches = body.data ?? [];

    // Guard against a server that ignores search_string and returns the lot:
    // a fingerprint is 12 hex chars, so a real match is rare and specific.
    return matches.length > 20 ? [] : matches;
  }

  /* -- writing -------------------------------------------------------- */

  /**
   * Creates a defect and returns it.
   *
   * VERIFY: Axosoft wraps create payloads in an `item` envelope on v5/v6.
   * If your instance rejects this, the error body names the offending field.
   */
  async createDefect(input: {
    name: string;
    description: string;
  }): Promise<AxosoftItem> {
    const item: Record<string, unknown> = {
      name: input.name,
      description: input.description,
      project: { id: this.config.projectId },
    };
    if (this.config.priorityId) item.priority = { id: this.config.priorityId };
    if (this.config.assignedToId) item.assigned_to = { id: this.config.assignedToId };
    if (this.config.releaseId) item.release = { id: this.config.releaseId };

    const body = await this.request<{ data?: AxosoftItem }>('/defects', {
      method: 'POST',
      body: JSON.stringify({ item }),
    });

    if (!body.data?.id) {
      throw new AxosoftError('Axosoft accepted the create but returned no defect id');
    }
    return body.data;
  }

  /** Adds a note to an existing defect — used when a known failure recurs. */
  async addComment(defectId: number, text: string): Promise<void> {
    await this.request(`/defects/${defectId}/notes`, {
      method: 'POST',
      body: JSON.stringify({ item: { note: text } }),
    });
  }

  /** Convenience for building a clickable link back to the defect. */
  defectUrl(id: number): string {
    return `${this.config.baseUrl.replace(/\/+$/, '')}/viewitem?id=${id}&type=defects`;
  }
}

async function safeText(res: Response): Promise<string> {
  try {
    return (await res.text()).slice(0, 500);
  } catch {
    return '<no body>';
  }
}

/** Reads configuration from the environment. Returns null if not configured. */
export function axosoftConfigFromEnv(): AxosoftConfig | null {
  const baseUrl = process.env.AXOSOFT_URL;
  const projectId = Number(process.env.AXOSOFT_PROJECT_ID);

  if (!baseUrl || !projectId) return null;

  return {
    baseUrl,
    apiVersion: process.env.AXOSOFT_API_VERSION ?? 'v5',
    token: process.env.AXOSOFT_TOKEN,
    clientId: process.env.AXOSOFT_CLIENT_ID,
    clientSecret: process.env.AXOSOFT_CLIENT_SECRET,
    username: process.env.AXOSOFT_USERNAME,
    password: process.env.AXOSOFT_PASSWORD,
    projectId,
    priorityId: numberOrUndefined(process.env.AXOSOFT_PRIORITY_ID),
    assignedToId: numberOrUndefined(process.env.AXOSOFT_ASSIGNED_TO_ID),
    releaseId: numberOrUndefined(process.env.AXOSOFT_RELEASE_ID),
  };
}

function numberOrUndefined(value: string | undefined): number | undefined {
  const n = Number(value);
  return Number.isFinite(n) && n > 0 ? n : undefined;
}
